language: ruby
rvm:
  - 2.0.0
  - 1.9.3

deploy:
  provider: heroku
  api_key: 564944ec-9b8d-4bc2-81f6-4ef46aaf8df3
  run: "rake db:migrate"

#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec